From Coq Require Import Strings.String.

(* Generated by theories/jessie/tools/js_to_coq_source.py.
   Source: theories/jessie/sources/makeCounter.js.
   Edit the .js file, not this generated Coq file. *)

Open Scope string_scope.

Definition makeCounter_source : string :=
  "const makeCounter = () => {
  let count = 0;
  return {
    incr: () => (count += 1),
    decr: () => (count -= 1),
  };
};
".
